### ISSUE TITLE
After editing a task - the feedback rating value and the Send button are still enabled 

### ISSUE THREAD

**Issue by vidyabhandary** [bradtraversy/feedback-app#1]
I am following this tutorial on Udemy and I noticed that after editing a feedback - the star rating remains the same as that of the feedback just edited and the Send button is enabled. They should both be cleared along with the text right ?

**Comment by bushblade** [comment]
Hi @vidyabhandary 
Is this an issue with your own code or did you clone this repository and see the issue?
If it is with your own code then please post in the Udemy Q&A and one of us will be along to help you.
There is a known in issue in the repository code whereby if you edit a feedback it is then not possible to add another feedback.
This has been fixed in the [bugfix](https://github.com/bradtraversy/feedback-app/tree/bugfix) branch of this repository so you may find that useful.

**Comment by vidyabhandary** [comment]
Hi @bushblade 
I cloned this repo and found the issue. But as suggested I have addressed the query in the Udemy course.

**Comment by bushblade** [comment]
Thanks yeah I saw your question. I'm not sure if it's a 'issue' or if that is the intended functionality to be honest. My feeling would be as you suggest and it should be reset to the default.

**Comment by vidyabhandary** [comment]
@bushblade - The changes resetting the rating and disabling the button worked ! Thanks.
